---
all:
  hosts:
    server:
        ansible_host: 127.0.0.1
        ansible_port: 2207
        ansible_private_key_file: /root/OTUS/Kazay/Stack_oversearch/.vagrant/machines/server/virtualbox/private_key
                      